### PR TITLE
Thread safety

### PR DESCRIPTION
**Pull request by dhardiman**
There's a few changes in here. First is that it's now using the `projCtx` to pass errors around. However, as we've effectively got static instances of the primary transformations we use, that's not really solving the problem, as despite the article on thread safety, it appears that proj.4 makes absolutely no guarantees on thread safety at all, and instead expects you to use one instance per thread. Well that sucks, so I've also wrapped the access to proj.4 in `@synchronized` blocks as well. I've then updated to the latest upstream version of proj, which isn't technically a release yet, so might be a bad idea, but that's allowed me to re-enable bitcode on this. I don't intend to ship this in production immediately though, we'll put it in to the app after we ship so we've got plenty of time to test it.

### CODE REVIEW

**Comment by roman-dzieciol** [comment]
The synchronized should be safe and not measurably slower from user's perspective. I assume there are no callbacks from proj4 into app that could deadlock. An alternative could be async queue-based api, but it's not always feasible.

LGTM

**Comment by dhardiman** [comment]
An async API would be horrible I think. Every single place we do these conversions we'd need to update an API to an asynchronous callback. The only alternative I can see is to confine those operations to their own `dispatch_queue_t` with `dispatch_sync` calls, but I'd rather we tried this out first. But as I say, I'd rather it spent a few weeks in test before we ship anything using it.

**Comment by roman-dzieciol** [comment]
Yea, synchronized should be better, unless there's some place where blocking a thread is no-go.

**Comment by dhardiman** [comment]
There shouldn't be any significant overhead added here. The issues we're seeing are already fairly rare in practice, so I'm not sure there's any problem with potentially blocking a thread for a minuscule amount of time. We shall see anyway. Unfortunately it's not a problem I've seen in development, so I suspect we'll need to ship it before we know for certain, but a couple of weeks stress testing it won't hurt.

**Comment by roman-dzieciol** [comment]
There shouldn't be issues even with blocking main thread for a bit. The changes in https://github.com/OrdnanceSurvey/os-maps-ios/commit/db6d92c80dbd7d154e7e999ab53f07aeedc8c0ba made it crash very often. Haven't really noticed this issue otherwise.

**Comment by dhardiman** [comment]
Me either, I just know we've got plenty of crash logs about it. Not so many that I'd take a risk shipping this without a good long test period anyway!

**Pull request merged**
